[light]
keyword = "#AF00DB"
keyword2 = "#0000FF"
function = "#795E26"
string = "#A31515"
number = "#098658"
comment = "#008000"
operator = "#000000"
type = "#267F99"
preprocessor = "#AF00DB"
namespace = "#267F99"
variable = "#001080"
punctuation = "#000000"
plain = "#1F2328"

[dark]
keyword = "#C586C0"
keyword2 = "#569CD6"
function = "#DCDCAA"
string = "#CE9178"
number = "#B5CEA8"
comment = "#6A9955"
operator = "#D4D4D4"
type = "#4EC9B0"
preprocessor = "#C586C0"
namespace = "#4EC9B0"
variable = "#9CDCFE"
punctuation = "#D4D4D4"
plain = "#D4D4D4"
