
[options]
extensions = ["md", "txt"]
detect_string = 'EXT="MD"'

[fonts]
body = "Arial"
body_size = 14
code = "Courier New"
code_size = 12

[colors.light]
background = "#AABBCC"
text = "#112233"

[colors.dark]
background = "#334455"
link = "#99AAFF"
